export const MOSTRAR_PRODUCTOS = "MOTRAR_PRODUCTOS";
export const MOSTRAR_PRODUCTO = "MOSTRAR_PRODUCTO";
export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const BUSCAR_PRODUCTO = "BUSCAR_PRODUCTO";